name: LocalManageStore
on:
  pull_request :
    branches : [ main ]
  push :
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        env:
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
          MONTH: "${{ steps.current-time.outputs.month }}"
          HOUR: "${{ steps.current-time.outputs.hour }}"
          MINUTE: "${{ steps.current-time.outputs.minute }}"
        with:
          # Artifact name
          name: LocalManageStore-${{ steps.current-time.outputs.minute }}-${{ steps.current-time.outputs.hour }}-${{ steps.current-time.outputs.day }}-${{ steps.current-time.outputs.month }}-${{ steps.current-time.outputs.year }}.apk
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/app-debug.apk